var nome, cpf, tel, nquartos, temploc, cidade, bairro;

function validateForm() {
    let nome = document.forms["cadastro"]["fname"].value;
    /*let cpf = document.forms["cadastro"]["CPF"].value;
    let tel = document.forms["cadastro"]["tel"].value;
    let nquartos = document.forms["cadastro"]["nquartos"].value;
    let temploc = document.forms["cadastro"]["PERIODO_LOC"].value;
    let cidade = document.forms["cadastro"]["cidade"].value;
    let bairro = document.forms["cadastro"]["bairro"].value;*/
      if (nome== "") {
    alert("todos os campos precisam ser preenchidos");
    return false;
    /* elif(cpf== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif(tel== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif(nquartos== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif(temploc== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif(bairro== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif(cidade== "")
    alert("todos os campos precisam ser preenchidos");
    return false;
    elif
    alert("cadastro efetuado com sucesso"); */
    }
}
alert(nome); 
